create extension if not exists "pgcrypto";

create type public.session_status as enum ('configured', 'active', 'completed');
create type public.transcript_speaker as enum ('candidate', 'interviewer');

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  created_at timestamptz not null default now()
);

create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  target_role text not null,
  job_description text,
  status public.session_status not null default 'configured',
  created_at timestamptz not null default now()
);

create table public.transcripts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  speaker public.transcript_speaker not null,
  text_content text not null,
  timestamp timestamptz not null default now()
);

create table public.evaluations (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.sessions(id) on delete cascade,
  overall_score int,
  star_method_feedback jsonb,
  communication_score int,
  strengths text[],
  weaknesses text[],
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.transcripts enable row level security;
alter table public.evaluations enable row level security;

create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

create policy "Users can insert own profile" on public.users
  for insert with check (auth.uid() = id);

create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can view own sessions" on public.sessions
  for select using (auth.uid() = user_id);

create policy "Users can insert own sessions" on public.sessions
  for insert with check (auth.uid() = user_id);

create policy "Users can update own sessions" on public.sessions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can delete own sessions" on public.sessions
  for delete using (auth.uid() = user_id);

create policy "Users can view own transcripts" on public.transcripts
  for select using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can insert own transcripts" on public.transcripts
  for insert with check (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can update own transcripts" on public.transcripts
  for update using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  ) with check (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can delete own transcripts" on public.transcripts
  for delete using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can view own evaluations" on public.evaluations
  for select using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can insert own evaluations" on public.evaluations
  for insert with check (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can update own evaluations" on public.evaluations
  for update using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  ) with check (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

create policy "Users can delete own evaluations" on public.evaluations
  for delete using (
    exists (
      select 1
      from public.sessions
      where public.sessions.id = session_id
        and public.sessions.user_id = auth.uid()
    )
  );

-- Automatically create a public.users profile row when a new auth user signs up.
-- This ensures the FK constraint on sessions.user_id is always satisfiable.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, name, email)
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Indexes for FK columns queried frequently
create index if not exists idx_sessions_user_id on public.sessions (user_id);
create index if not exists idx_transcripts_session_id on public.transcripts (session_id);
create index if not exists idx_evaluations_session_id on public.evaluations (session_id);
